POST http://fooo.com
Content-Type: application/json

###

POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "to": "eCSXCER8nHs:APA91bFTJfD7VLxpdfbMdRwqdmXPgPiqMB5BRL4DDmGnRPLnFTtvYY2WBp__-zzIAKrzr71AWrInldQxNlo39KUOLoo2PyV1j_mPY9QRwVgbJaYLS9sxErDBdy-ySrKNUkFq_177tU92",
  "data": {
//"hello": "This is a Firebase Cloud Messaging Device Group Message!"
    "message": {
      "title": "hey dude",
      "notification": {
        "body": "This is an FCM notification message!",
        "title": "FCM Message"
      }
    },
    "icon":"https://www.tourdom.ru/upload/iblock/404/404fddb2797c033b087c4247630b2db7.jpg"
  }
}

###

//for chrome
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "eCSXCER8nHs:APA91bFTJfD7VLxpdfbMdRwqdmXPgPiqMB5BRL4DDmGnRPLnFTtvYY2WBp__-zzIAKrzr71AWrInldQxNlo39KUOLoo2PyV1j_mPY9QRwVgbJaYLS9sxErDBdy-ySrKNUkFq_177tU92"
}

###

//for firefox
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "fJr_I0K_4SU:APA91bGT0U_lcroqqVRDwkp1vFnAS8KjS2EsZQHq1cl4aOZjKrFRpa0xaVd9z9VYCLwQzeOoTLeTc7J-DHV0R7P8BzBq6__OoJCu2NptV5ZSEYMLhEtmbEtKrTbOOIxGjJBeRoIh9IxE"
}

###

//for edge
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "cElLgftwJV8:APA91bEBbse-LToWmdKeJMDPgt6libQm9SxaeBiW5qYjRZWZWbjJuTKzCWIAIKUwgY1cUyLxgm02u4v2mTIHZoktXnFgs8eNgrSrw9fucVRcXopAnN0NyX_FEeEXE_uZ66FyHFaS4J0R"
}

###
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: bearer key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "group": {
    "app_id": "push-api-test-65c23",
    "name": "VIP-users",
    "send_rate": 180
  }
}

###
//creating group
POST https://fcm.googleapis.com/fcm/notification
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA
project_id: 301131752481

{
  "operation": "create",
  "notification_key_name": "appUser-Chris",
  "registration_ids": ["fJr_I0K_4SU:APA91bGT0U_lcroqqVRDwkp1vFnAS8KjS2EsZQHq1cl4aOZjKrFRpa0xaVd9z9VYCLwQzeOoTLeTc7J-DHV0R7P8BzBq6__OoJCu2NptV5ZSEYMLhEtmbEtKrTbOOIxGjJBeRoIh9IxE",
    "fSogKMsCfD0:APA91bEGGt3N93rXZfyS4qq-JxV6A4k9yYRxbrKqktoUfdaqxiDAIQcfVABMZa45x1FnZO2JRuLlF3PC44t9vshrmy1OYFNJqrn6mnMulh_HxgViv5BN6f_X37HoJjefJYHjUebypIy5",
    "cElLgftwJV8:APA91bEBbse-LToWmdKeJMDPgt6libQm9SxaeBiW5qYjRZWZWbjJuTKzCWIAIKUwgY1cUyLxgm02u4v2mTIHZoktXnFgs8eNgrSrw9fucVRcXopAnN0NyX_FEeEXE_uZ66FyHFaS4J0R"
  ]
}

###

POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "APA91bENUGhLre6_Sqm8O5BowwshT5pGFcKD_5GURp5SkN36pXL4G9Yif7oPpM0GJ1llbLyi5aqSsppNtRhpICDkw7WSd_7yKKDhjzHfLbfiU7-HsATspBI"
}

###
