POST http://fooo.com
Content-Type: application/json

###

POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "to": "cFSo3fuQAk8:APA91bFp6kjIednkOPcyqLQ9v3mddUPZhGckoToCxnsJJmbfpfu7jjb3Kwgqez_RuijjpURQentD9ycgdCuQtx34vXbPacM3fewtMsyKV1_PJyqfyQrkG9wEJsIdEXI8-bOjgV8p5gW6",
  "data": {
//"hello": "This is a Firebase Cloud Messaging Device Group Message!"
    "message": {
      "title": "hey dude",
      "notification": {
        "body": "This is an FCM notification message!",
        "title": "FCM Message"
      }
    },
    "icon":"https://www.tourdom.ru/upload/iblock/404/404fddb2797c033b087c4247630b2db7.jpg"
  }
}

###

//for chrome
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "cFSo3fuQAk8:APA91bFp6kjIednkOPcyqLQ9v3mddUPZhGckoToCxnsJJmbfpfu7jjb3Kwgqez_RuijjpURQentD9ycgdCuQtx34vXbPacM3fewtMsyKV1_PJyqfyQrkG9wEJsIdEXI8-bOjgV8p5gW6"
}

###

//for firefox
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "ev94j-pk_SE:APA91bEGPEfKe62rNqBASNAVriEi7T7P6WG4NbKhkvmTsofjN7OgtmF4Jr82HUAnK0xl1mcwr-B2Y8KS6Zo6MqQwkuy2dRXZ_6JyzYk9shO1s7ZKNJRTpoI-5Ze8aEU-tkB4XJxE32ns"
}

###

//for edge
POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAARhzZ5CE:APA91bFyqiQKF5hDfn8Cp5bWd6VFMqMpUtoApf1mYP7IxtKF2MpRpS-O9FCwFJFwEmI9cq1IYMRVYz6ZgKpbYgwroHFKnD7ChO79CAgOTRXOurEUV6mMHKkZQM7bbUzaldfEjenMLhAA

{
  "notification": {
    "title": "hey dudezzzz",
    "body": "keep prayin'",
    "icon": "https://www.meme-arsenal.com/memes/9e37cdd5db9ad2b0d0a4a94964cc3526.jpg"
  },
  "to": "cElLgftwJV8:APA91bEBbse-LToWmdKeJMDPgt6libQm9SxaeBiW5qYjRZWZWbjJuTKzCWIAIKUwgY1cUyLxgm02u4v2mTIHZoktXnFgs8eNgrSrw9fucVRcXopAnN0NyX_FEeEXE_uZ66FyHFaS4J0R"
}

###